const ROLE = {
  GUEST: "GUEST",
  USER: "USER",
  ADMIN: "ADMIN",
  MASTER: "MASTER",
};

const ROLE_LEVEL = {
  GUEST: 0,
  USER: 1,
  ADMIN: 2,
  MASTER: 3,
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCK: "BLOCK",
  PENDING: "PENDING",
  DORMANT: "DORMANT",
  DELETE: "DELETE",
};

const STATUS = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  PENDING: "PENDING",
  REPLACED: "REPLACED",
};

const RESULT = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
};

const EVENT_TYPE = {
  INFO: "INFO",
  TRACE: "TRACE",
  DEBUG: "DEBUG",
  WARN: "WARN",
  ERROR: "ERROR",
};

const SERVICE_TYPE = {
  USER: "USER",
  GROUP: "GROUP",
  FILE: "FILE",
  RESOURCE: "RESOURCE",
  STORAGE: "STORAGE",
  SNAPSHOT: "SNAPSHOT",
  RESTORE: "RESTORE",
  SETTING: "SETTING",
};

const FILE_EVENT = {
  CREATE: "CREATE",
  UPLOAD: "UPLOAD",
  RENAME: "RENAME",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  MOVE: "MOVE",
  COPY: "COPY",
};

const FILE_STATUS = {
  UNCHANGED: "UNCHANGED",
  CREATED: "CREATED",
  MODIFIED: "MODIFIED",
  DELETED: "DELETED",
};

const BACKUP_TYPE = {
  FULL: 0,
  INCREMENTAL: 1,
};

const CATEGORY = {
  AUTH: "AUTH",
  DASHBOARD: "DASHBOARD",
  FILE: "FILE",
  RESOURCE: "RESOURCE",
  STORAGE: "STORAGE",
  SNAPSHOT: "SNAPSHOT",
  RESTORE: "RESTORE",
  USER: "USER",
  GROUP: "GROUP",
  POLICY: "POLICY",
  EVENT: "EVENT",
  LOG: "LOG",
  SETTING: "SETTING",
  SYSTEM: "SYSTEM",
};

const METHOD = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
  PATCH: "PATCH",
};

const ACCESS = {
  NO_ACCESS: "NO_ACCESS",
  READ_ONLY: "READ_ONLY",
  READ_WRITE: "READ_WRITE",
  FULL_ACCESS: "FULL_ACCESS",
};

const ACCESS_LEVEL = {
  NO_ACCESS: 0,
  READ_ONLY: 1,
  READ_WRITE: 2,
  FULL_ACCESS: 3,
};

const USAGE_EVENT = {
  DAILY: "DAILY",
  SNAPSHOT: "SNAPSHOT",
  RESTORE: "RESTORE",
  SYNC: "SYNC",
};

module.exports = {
  ROLE,
  ROLE_LEVEL,
  USER_STATUS,
  STATUS,
  RESULT,
  EVENT_TYPE,
  SERVICE_TYPE,
  FILE_EVENT,
  FILE_STATUS,
  BACKUP_TYPE,
  CATEGORY,
  METHOD,
  ACCESS,
  ACCESS_LEVEL,
  USAGE_EVENT,
};
